spring.application.name=CorpBot

# Ollama
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.embedding.model=nomic-embed-text

spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-3-flash-preview
spring.cloud.ai.retry.initial-interval=2000
spring.cloud.ai.retry.max-attempts=3
spring.cloud.ai.retry.multiplier=2.0

spring.datasource.hikari.connection-init-sql=SET TIME ZONE 'Asia/Kolkata'
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${POSTGRES_URL}
spring.datasource.username=${POSTGRES_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.data.redis.host=localhost
spring.data.redis.port=6379