spring.application.name=CorpBot

spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=openai/gpt-oss-120b
spring.ai.openai.embedding.enabled=false

# Ollama
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.embedding.model=nomic-embed-text
spring.ai.ollama.embedding.enabled=true

spring.datasource.hikari.connection-init-sql=SET TIME ZONE 'Asia/Kolkata'
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${POSTGRES_URL}
spring.datasource.username=${POSTGRES_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.data.redis.host=localhost
spring.data.redis.port=6379